name: main


on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  check-path:
    uses: ./.github/workflows/check-path.yml


  frontend:
    needs: [check-path]
    uses: ./.github/workflows/frontend.yml
    if: needs.check-path.outputs.frontend


  backend:
    needs: [check-path]
    uses: ./.github/workflows/backend.yml
    if: needs.check-path.outputs.backend


  deploy-staging:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    concurrency: staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: staging
      url: https://dev.codeforpoznan.pl
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - uses: turskislab/site/.github/actions/deploy@master
        env:
          AWS_RESOURCE_NAME: ${{ secrets.AWS_RESOURCE_NAME }}
          AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
